// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MissingZoneApi.Entities
{
    public partial class Comment
    {
        public int CommentId { get; set; }
        public int? MissingPostId { get; set; }
        public string UserId { get; set; }
        public string Comment1 { get; set; }
        public bool? IsVerified { get; set; }
        public DateTime? CreatedDate { get; set; }
    }
}