// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MissingZoneApi.Entities
{
    public partial class MissingPost
    {
        public int MissingPostId { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public int? Photos { get; set; }
        public string ContactInfo { get; set; }
        public string UserId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FatherName { get; set; }
        public DateTime? BirthDate { get; set; }
        public DateTime? CreateDate { get; set; }
        public string City { get; set; }
        public string Coordinates { get; set; }
    }
}