// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MissingZoneApi.Entities
{
    public partial class Mp2v
    {
        public int MissingPostToVolunteerId { get; set; }
        public int? VolunteerId { get; set; }
        public int? MissingPostId { get; set; }
    }
}