// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MissingZoneApi.Entities
{
    public partial class Photo
    {
        public int PhotoId { get; set; }
        public int? MissingPostId { get; set; }
        public string Content { get; set; }
    }
}