// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MissingZoneApi.Entities
{
    public partial class Volunteer
    {
        public string Email { get; set; }
        public string Password { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public byte[] Photo { get; set; }
        public bool? IsVerified { get; set; }
        public string OrganizationName { get; set; }
        public string Phone { get; set; }
    }
}